package ExceptionHandling;

public class e25
{

	public static void main(String[] args)
	{
	
	/*	try
		{
			System.out.println(1/0);
		}
		catch(RuntimeException | ArithmeticException object) here RuntimeException is father of ArithmeticException
		{                                                    so no need to specify Arithmetic Exception
			                                                 so it shows error 
		}
	
	*/

	}

}
